// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OLC.Cases.Api.Data;

namespace OLC.Cases.Api.Migrations
{
    [DbContext(typeof(LegalCaseContext))]
    partial class LegalCaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OLC.Cases.Api.Models.Case", b =>
                {
                    b.Property<string>("CaseNumber")
                        .HasColumnType("varchar(24)");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NameOfTheResponsible")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime");

                    b.HasKey("CaseNumber");

                    b.ToTable("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
